FROM java:8

MAINTAINER Jia Zhai <jia.zhai@emc.com>

RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y unzip
RUN mkdir -p /opt
RUN cd /opt
RUN wget https://github.com/twitter/distributedlog/releases/download/0.3.51-RC1/distributedlog-service-3ff9e33fa577f50eebb8ee971ddb265c971c3717.zip
RUN unzip distributedlog-service-3ff9e33fa577f50eebb8ee971ddb265c971c3717.zip
RUN mkdir -p /opt/dl_all
RUN mv distributedlog-service /opt/dl_all/

ENV ZK_URL master.mesos:2181
ENV bookiePort 3181

# all execute-able bin, download from distributed_log
WORKDIR /opt/dl_all

# After container up, Following instructions to build bookie cluster
# http://distributedlog.incubator.apache.org/docs/latest/deployment/cluster.html
COPY /entry_point.sh .
ENTRYPOINT ./entry_point.sh

