FROM java:8

MAINTAINER Prabha Veerubhotla [Vijayalakshmi.Veerubhotla@emc.com]

COPY entrypoint_controller.sh /opt/
COPY /controller/server/build/distributions/   /opt/controller/

WORKDIR /opt/controller/

RUN tar -xvf /opt/controller/server.tar

RUN rm /opt/controller/server.tar
RUN rm /opt/controller/server.zip

ENTRYPOINT [ "/opt/entrypoint_controller.sh" ]


