FROM java:8

#
#  Copyright (c) 2017 Dell Inc., or its subsidiaries.
#

MAINTAINER Prabha Veerubhotla [Vijayalakshmi.Veerubhotla@emc.com]

COPY /controller/server/build/distributions/   /opt/controller/

WORKDIR /opt/controller/

RUN tar -xvf /opt/controller/server.tar

RUN rm /opt/controller/server.tar
RUN rm /opt/controller/server.zip

ENTRYPOINT [ "/opt/controller/server/bin/server" ]

