# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
---
- include_vars: data/variable.yml

- name: Create zk work dir
  shell: mkdir -p /opt/zk
  sudo: yes

- name: move zookeeper
  shell: cp -r zookeeper-3.5.1-alpha /opt/zk/
  sudo: yes

- name: Untar bk
  shell: tar -xvf bookkeeper-server-4.4.0-bin.tar.gz

- name: Create bk work dir
  shell: mkdir -p /opt/bk_all
  sudo: yes

- name: Move bk under bk_all folder
  shell: mv bookkeeper-server-4.4.0/ /opt/bk_all/
  sudo: yes

- name: Copy install script
  copy:
    src: install-bk.sh
    dest: /opt/bk_all
  sudo: yes

- name: Add exec mode on script
  shell: chmod +x /opt/bk_all/install-bk.sh
  sudo: yes

- name: Format the volume one
  shell: mkfs -t ext4 /dev/nvme0n1
  sudo: yes
  when: high_performance_mode == true

- name: Create mount point one
  shell: mkdir -p /bk/ledgers
  sudo: yes
  when: high_performance_mode == true

- name: Mount the volume one
  shell: mount /dev/nvme0n1 /bk/ledgers
  sudo: yes
  when: high_performance_mode == true

- name: Format volume two
  shell: mkfs -t ext4 /dev/nvme1n1
  sudo: yes
  when: high_performance_mode == true

- name: Create mount point two
  shell: mkdir /bk/journal
  sudo: yes
  when: high_performance_mode == true

- name: Mount the volume two
  shell: mount /dev/nvme1n1 /bk/journal
  sudo: yes
  when: high_performance_mode == true

- name: Run install script
  shell: /opt/bk_all/install-bk.sh
  sudo: yes
