#
# Copyright Pravega Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
- name: Untar zookeeper
  command: tar -xvf /zookeeper-3.5.1-alpha.tar.gz

- name: Configure Zookeeper
  template: src=zoo.cfg.j2 dest=/root/zookeeper-3.5.1-alpha/conf/zoo.cfg

- name: Check if Zookeeper has been initialized
  stat: path={{ zookeeper_data_dir }}/myid
  register: zookeeper_id_file

- name: Initialize Zookeeper
  command: /root/zookeeper-3.5.1-alpha/bin/zkServer-initialize.sh init --force --myid={{ myid }}
  when: not zookeeper_id_file.stat.exists
  sudo: yes

- name: Run zookeeper
  command: /root/zookeeper-3.5.1-alpha/bin/zkServer.sh start
  sudo: yes
